using System;
using WixSharp;

class Script
{
    static public void Main()
    {
        const string ProgramFolderName = "Certificate Registry 3";

        Compiler.WixLocation = @"..\packages\WixSharp.wix.bin.3.11.2\tools\bin";

        var project = new Project("CertificateRegistry3",
                        // папка установки
                        new Dir($@"%ProgramFiles%\{ProgramFolderName}",
                            // файлы программы
                            new File(@"..\CertificateRegistry3\bin\Release\CertificateRegistry3.exe"),
                            new File(@"..\CertificateRegistry3\bin\Release\CertificateRegistry3.exe.config"),
                            new File(@"..\CertificateRegistry3\bin\Release\EntityFramework.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\EntityFramework.SqlServer.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\Microsoft.Bcl.AsyncInterfaces.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\Microsoft.Win32.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\netstandard.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\Npgsql.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.AppContext.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Buffers.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Collections.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Collections.Concurrent.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Collections.NonGeneric.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Collections.Specialized.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.ComponentModel.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.ComponentModel.EventBasedAsync.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.ComponentModel.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.ComponentModel.TypeConverter.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Console.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Data.Common.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Data.SQLite.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Data.SQLite.EF6.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Data.SQLite.Linq.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.Contracts.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.Debug.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.FileVersionInfo.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.Process.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.StackTrace.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.TextWriterTraceListener.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.Tools.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.TraceSource.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Diagnostics.Tracing.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Drawing.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Dynamic.Runtime.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Globalization.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Globalization.Calendars.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Globalization.Extensions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.Compression.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.Compression.ZipFile.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.FileSystem.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.FileSystem.DriveInfo.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.FileSystem.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.FileSystem.Watcher.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.IsolatedStorage.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.MemoryMappedFiles.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.Pipes.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.IO.UnmanagedMemoryStream.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Linq.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Linq.Expressions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Linq.Parallel.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Linq.Queryable.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Memory.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.Http.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.NameResolution.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.NetworkInformation.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.Ping.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.Requests.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.Security.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.Sockets.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.WebHeaderCollection.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.WebSockets.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Net.WebSockets.Client.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Numerics.Vectors.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.ObjectModel.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Reflection.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Reflection.Extensions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Reflection.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Resources.Reader.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Resources.ResourceManager.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Resources.Writer.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.CompilerServices.VisualC.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Extensions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Handles.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.InteropServices.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.InteropServices.RuntimeInformation.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Numerics.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Serialization.Formatters.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Serialization.Json.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Serialization.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Runtime.Serialization.Xml.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Claims.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Cryptography.Algorithms.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Cryptography.Csp.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Cryptography.Encoding.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Cryptography.Primitives.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Cryptography.X509Certificates.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.Principal.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Security.SecureString.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Text.Encoding.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Text.Encoding.Extensions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Text.Encodings.Web.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Text.Json.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Text.RegularExpressions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Channels.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Overlapped.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Tasks.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Tasks.Extensions.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Tasks.Parallel.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Thread.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.ThreadPool.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Threading.Timer.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.ValueTuple.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Xml.ReaderWriter.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Xml.XDocument.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Xml.XmlDocument.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Xml.XmlSerializer.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Xml.XPath.dll"),
                            new File(@"..\CertificateRegistry3\bin\Release\System.Xml.XPath.XDocument.dll"),

                            // вложенные папки
                            new Dir(@"x64", new File(@"..\CertificateRegistry3\bin\Release\x64\SQLite.Interop.dll")),
                            new Dir(@"x86", new File(@"..\CertificateRegistry3\bin\Release\x86\SQLite.Interop.dll"))
                        ),
                        // папка с ярлыками в меню
                        new Dir($@"%ProgramMenu%\{ProgramFolderName}",
                            new ExeFileShortcut(ProgramFolderName, "[INSTALLDIR]CertificateRegistry3.exe", arguments: ""),
                            new ExeFileShortcut("Uninstall program", "[System64Folder]msiexec.exe", arguments: "/x [ProductCode]")),
                        new Dir(@"%Desktop%",
                            new ExeFileShortcut(ProgramFolderName, "[INSTALLDIR]CertificateRegistry3.exe", arguments: ""))
                    );

        project.GUID = new Guid("6978ac45-699b-4e9c-a333-0b4db2e1ef47");
        project.UI = WUI.WixUI_InstallDir;
        project.ControlPanelInfo.InstallLocation = "[INSTALLDIR]";
        project.LicenceFile = "license.rtf";

        Compiler.BuildMsi(project);
    }
}