using System;
using WixSharp;

class Script
{
    static public void Main()
    {
        File[] files =
        {
            new File(@"CertificateRegistry3.exe"),
            new File(@"CertificateRegistry3.exe.config"),
            new File(@"certificates.sqlite"),
            new File(@"EntityFramework.dll"),
            new File(@"EntityFramework.SqlServer.dll"),
            new File(@"Microsoft.Bcl.AsyncInterfaces.dll"),
            new File(@"Microsoft.Win32.Primitives.dll"),
            new File(@"netstandard.dll"),
            new File(@"Npgsql.dll"),
            new File(@"registry.html"),
            new File(@"System.AppContext.dll"),
            new File(@"System.Buffers.dll"),
            new File(@"System.Collections.dll"),
            new File(@"System.Collections.Concurrent.dll"),
            new File(@"System.Collections.NonGeneric.dll"),
            new File(@"System.Collections.Specialized.dll"),
            new File(@"System.ComponentModel.dll"),
            new File(@"System.ComponentModel.EventBasedAsync.dll"),
            new File(@"System.ComponentModel.Primitives.dll"),
            new File(@"System.ComponentModel.TypeConverter.dll"),
            new File(@"System.Console.dll"),
            new File(@"System.Data.Common.dll"),
            new File(@"System.Data.SQLite.dll"),
            new File(@"System.Data.SQLite.EF6.dll"),
            new File(@"System.Data.SQLite.Linq.dll"),
            new File(@"System.Diagnostics.Contracts.dll"),
            new File(@"System.Diagnostics.Debug.dll"),
            new File(@"System.Diagnostics.FileVersionInfo.dll"),
            new File(@"System.Diagnostics.Process.dll"),
            new File(@"System.Diagnostics.StackTrace.dll"),
            new File(@"System.Diagnostics.TextWriterTraceListener.dll"),
            new File(@"System.Diagnostics.Tools.dll"),
            new File(@"System.Diagnostics.TraceSource.dll"),
            new File(@"System.Diagnostics.Tracing.dll"),
            new File(@"System.Drawing.Primitives.dll"),
            new File(@"System.Dynamic.Runtime.dll"),
            new File(@"System.Globalization.dll"),
            new File(@"System.Globalization.Calendars.dll"),
            new File(@"System.Globalization.Extensions.dll"),
            new File(@"System.IO.dll"),
            new File(@"System.IO.Compression.dll"),
            new File(@"System.IO.Compression.ZipFile.dll"),
            new File(@"System.IO.FileSystem.dll"),
            new File(@"System.IO.FileSystem.DriveInfo.dll"),
            new File(@"System.IO.FileSystem.Primitives.dll"),
            new File(@"System.IO.FileSystem.Watcher.dll"),
            new File(@"System.IO.IsolatedStorage.dll"),
            new File(@"System.IO.MemoryMappedFiles.dll"),
            new File(@"System.IO.Pipes.dll"),
            new File(@"System.IO.UnmanagedMemoryStream.dll"),
            new File(@"System.Linq.dll"),
            new File(@"System.Linq.Expressions.dll"),
            new File(@"System.Linq.Parallel.dll"),
            new File(@"System.Linq.Queryable.dll"),
            new File(@"System.Memory.dll"),
            new File(@"System.Net.Http.dll"),
            new File(@"System.Net.NameResolution.dll"),
            new File(@"System.Net.NetworkInformation.dll"),
            new File(@"System.Net.Ping.dll"),
            new File(@"System.Net.Primitives.dll"),
            new File(@"System.Net.Requests.dll"),
            new File(@"System.Net.Security.dll"),
            new File(@"System.Net.Sockets.dll"),
            new File(@"System.Net.WebHeaderCollection.dll"),
            new File(@"System.Net.WebSockets.dll"),
            new File(@"System.Net.WebSockets.Client.dll"),
            new File(@"System.Numerics.Vectors.dll"),
            new File(@"System.ObjectModel.dll"),
            new File(@"System.Reflection.dll"),
            new File(@"System.Reflection.Extensions.dll"),
            new File(@"System.Reflection.Primitives.dll"),
            new File(@"System.Resources.Reader.dll"),
            new File(@"System.Resources.ResourceManager.dll"),
            new File(@"System.Resources.Writer.dll"),
            new File(@"System.Runtime.dll"),
            new File(@"System.Runtime.CompilerServices.Unsafe.dll"),
            new File(@"System.Runtime.CompilerServices.VisualC.dll"),
            new File(@"System.Runtime.Extensions.dll"),
            new File(@"System.Runtime.Handles.dll"),
            new File(@"System.Runtime.InteropServices.dll"),
            new File(@"System.Runtime.InteropServices.RuntimeInformation.dll"),
            new File(@"System.Runtime.Numerics.dll"),
            new File(@"System.Runtime.Serialization.Formatters.dll"),
            new File(@"System.Runtime.Serialization.Json.dll"),
            new File(@"System.Runtime.Serialization.Primitives.dll"),
            new File(@"System.Runtime.Serialization.Xml.dll"),
            new File(@"System.Security.Claims.dll"),
            new File(@"System.Security.Cryptography.Algorithms.dll"),
            new File(@"System.Security.Cryptography.Csp.dll"),
            new File(@"System.Security.Cryptography.Encoding.dll"),
            new File(@"System.Security.Cryptography.Primitives.dll"),
            new File(@"System.Security.Cryptography.X509Certificates.dll"),
            new File(@"System.Security.Principal.dll"),
            new File(@"System.Security.SecureString.dll"),
            new File(@"System.Text.Encoding.dll"),
            new File(@"System.Text.Encoding.Extensions.dll"),
            new File(@"System.Text.Encodings.Web.dll"),
            new File(@"System.Text.Json.dll"),
            new File(@"System.Text.RegularExpressions.dll"),
            new File(@"System.Threading.dll"),
            new File(@"System.Threading.Overlapped.dll"),
            new File(@"System.Threading.Tasks.dll"),
            new File(@"System.Threading.Tasks.Extensions.dll"),
            new File(@"System.Threading.Tasks.Parallel.dll"),
            new File(@"System.Threading.Thread.dll"),
            new File(@"System.Threading.ThreadPool.dll"),
            new File(@"System.Threading.Timer.dll"),
            new File(@"System.ValueTuple.dll")
        };
        var project = new Project("CertificateRegistry3",
                          new Dir(@"%ProgramFiles%\Certificate Registry 3",
                              files));

        project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
        project.UI = WUI.WixUI_InstallDir;

        Compiler.BuildMsi(project);
    }
}